name: run-selenium-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver (Chrome for Testing)
      run: |
        CHROME_VERSION=$(google-chrome --version | sed 's/[^0-9.]//g')
        echo "Detected Chrome version: $CHROME_VERSION"

        DRIVER_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chromedriver-linux64.zip"

        echo "Downloading ChromeDriver from: $DRIVER_URL"
        wget -N $DRIVER_URL -O chromedriver.zip

        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Install pip packages
      run: |
        pip install --upgrade pip
        pip install selenium pytest openpyxl pytest-html allure-pytest

    - name: Start Xvfb
      run: |
        sudo Xvfb :99 -ac &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Upload debug artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: irctc-debug
        path: |
          /tmp/*.html
          /tmp/*.png
